// <auto-generated />
using Meshur_Sehirler_CF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meshur_Sehirler_CF.Migrations
{
    [DbContext(typeof(AnadoluContext))]
    [Migration("20230622074017_Ilk")]
    partial class Ilk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Meshur_Sehirler_CF.Data.Ozellik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SehirId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SehirId");

                    b.ToTable("Ozellikler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Karpuz",
                            SehirId = 21
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Kayısı",
                            SehirId = 44
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mantı",
                            SehirId = 38
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Pastıma",
                            SehirId = 38
                        });
                });

            modelBuilder.Entity("Meshur_Sehirler_CF.Data.Sehir", b =>
                {
                    b.Property<int>("Plaka")
                        .HasColumnType("int");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Plaka");

                    b.ToTable("Sehirler");

                    b.HasData(
                        new
                        {
                            Plaka = 21,
                            Ad = "Diyarbakır"
                        },
                        new
                        {
                            Plaka = 44,
                            Ad = "Malatya"
                        },
                        new
                        {
                            Plaka = 38,
                            Ad = "Kayseri"
                        });
                });

            modelBuilder.Entity("Meshur_Sehirler_CF.Data.Ozellik", b =>
                {
                    b.HasOne("Meshur_Sehirler_CF.Data.Sehir", "Sehir")
                        .WithMany("Ozellikler")
                        .HasForeignKey("SehirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sehir");
                });

            modelBuilder.Entity("Meshur_Sehirler_CF.Data.Sehir", b =>
                {
                    b.Navigation("Ozellikler");
                });
#pragma warning restore 612, 618
        }
    }
}
